## CS115 Introduction to Programming in Python 
### Lab 09 

*Lab Objectives:*  Numpy.

*Instructions:* 

- In this lab, you will use the Jupyter Notebook.

- Complete the questions in the spaces provided and upload the solution to Moodle when finished.

*NOTE:* For the following questions, you should not use loops or if statements!

1) Download the files *country_data.csv*, *01_indicator.csv* and *02_indicator.csv* from Moodle. The files are tab delimited, and the data in each file is parallel.  For example, row 1 in the indicators files corresponds to the country in the country file.  Review the data in each file before proceeding.


2) Download this file *lab9.ipynb* as *yourname_Lab09.ipynb* that does the following: 

a. First import numpy

In [6]:
import numpy as np

b. import the data from the files into 3 separate numpy arrays.

- country stores country and region data

In [63]:
country_data = np.loadtxt("country_data.txt",skiprows=1,dtype="str",delimiter="\t",)
country_data


array([['South Asia', 'Afghanistan'],
       ['Central and Eastern Europe', 'Albania'],
       ['Middle East and North Africa', 'Algeria'],
       ['Latin America and Caribbean', 'Argentina'],
       ['Commonwealth of Independent States', 'Armenia'],
       ['North America and ANZ', 'Australia'],
       ['Western Europe', 'Austria'],
       ['Commonwealth of Independent States', 'Azerbaijan'],
       ['Middle East and North Africa', 'Bahrain'],
       ['South Asia', 'Bangladesh'],
       ['Commonwealth of Independent States', 'Belarus'],
       ['Western Europe', 'Belgium'],
       ['Sub-Saharan Africa', 'Benin'],
       ['Latin America and Caribbean', 'Bolivia'],
       ['Central and Eastern Europe', 'Bosnia and Herzegovina'],
       ['Sub-Saharan Africa', 'Botswana'],
       ['Latin America and Caribbean', 'Brazil'],
       ['Central and Eastern Europe', 'Bulgaria'],
       ['Sub-Saharan Africa', 'Burkina Faso'],
       ['Sub-Saharan Africa', 'Burundi'],
       ['Southeast Asia', 'Ca

- ind_01 stores the indicators from the 01_indicator_one file

In [49]:
ind_01 = np.loadtxt("01_indicator.txt",dtype="float",skiprows=1,,delimiter="\t")
ind_01

array([[ 9.4700e-01,  7.0807e+01,  8.5800e-01, -2.0800e-01,  8.6800e-01],
       [ 9.4800e-01,  7.1400e+01,  9.4900e-01, -1.0100e-01,  8.0600e-01],
       [ 8.2100e-01,  6.3813e+01,  8.6900e-01,  2.5700e-01,  9.1700e-01],
       [ 9.3600e-01,  6.9201e+01,  7.6600e-01, -1.2400e-01,  9.1100e-01],
       [ 9.3500e-01,  6.7906e+01,  7.7300e-01, -2.0300e-01,  8.2600e-01],
       [ 9.4100e-01,  6.8800e+01,  9.0900e-01, -1.0600e-01,  5.2700e-01],
       [ 8.9800e-01,  6.9702e+01,  8.4100e-01, -1.6500e-01,  7.3500e-01],
       [ 8.3200e-01,  6.7355e+01,  8.4500e-01, -2.1900e-01,  9.3800e-01],
       [ 8.7300e-01,  6.8600e+01,  7.7800e-01,  2.0000e-03,  8.3500e-01],
       [ 9.2700e-01,  6.7100e+01,  7.1500e-01, -1.6200e-01,  8.0000e-01],
       [ 9.4300e-01,  6.8000e+01,  7.5500e-01, -1.8600e-01,  8.7600e-01],
       [ 9.2400e-01,  7.0799e+01,  7.5400e-01, -1.1800e-01,  9.3900e-01],
       [ 8.7000e-01,  6.8098e+01,  7.0600e-01,  1.1300e-01,  9.3100e-01],
       [ 8.5800e-01,  6.8699e+01,  7.0

- ind_02 stores the indicators from the 02_indicator file

In [55]:
ind_02 = np.loadtxt("02_indicator.txt",dtype="float",skiprows=1,delimiter="\t")
ind_02

array([10.556, 10.529,  9.318, 10.369, 10.499, 10.481, 10.382, 10.284,
        9.787, 10.315, 10.358, 10.217,  9.59 ,  9.94 , 10.016,  9.52 ,
        9.693,  8.836, 10.155,  9.454,  8.538,  9.853, 10.189,  8.091,
        9.487,  9.569,  9.629,  9.585,  9.436, 10.871, 10.611, 10.651,
        9.4  , 11.   ,  9.673,  9.88 ,  9.053,  9.966,  9.577,  9.859,
        9.186, 10.35 , 10.071,  9.054,  9.557,  8.62 ,  9.962,  8.648,
        9.458,  9.313,  9.046,  9.448,  9.802,  9.073,  7.477, 10.575,
       10.669, 11.085, 10.743, 10.817,  9.622, 10.24 ,  8.903,  9.342,
        9.24 ,  9.584,  9.266,  9.626,  8.485,  9.182,  9.367,  7.578,
       10.643, 10.796, 10.776, 11.023,  8.12 ,  9.826,  8.454,  8.458,
        9.47 ,  8.755,  7.695, 11.488,  9.805,  9.076,  8.973, 10.238,
        9.365,  8.947,  8.36 ,  8.541, 10.008,  8.117,  8.551,  8.189,
        8.118,  8.58 ,  7.098,  7.686,  8.087,  7.838,  9.403,  9.603,
        7.678,  7.158,  8.533,  7.744,  7.677,  7.288,  8.361,  9.161,
      

c. Create a new array *ind_data* where the first column is *02_indicator data* and the remaining columns are from *01_indicator*


In [56]:
ind_data = np.hstack([ind_02.reshape(len(ind_02),1),ind_01,])
ind_data

array([[ 1.0556e+01,  9.4700e-01,  7.0807e+01,  8.5800e-01, -2.0800e-01,
         8.6800e-01],
       [ 1.0529e+01,  9.4800e-01,  7.1400e+01,  9.4900e-01, -1.0100e-01,
         8.0600e-01],
       [ 9.3180e+00,  8.2100e-01,  6.3813e+01,  8.6900e-01,  2.5700e-01,
         9.1700e-01],
       [ 1.0369e+01,  9.3600e-01,  6.9201e+01,  7.6600e-01, -1.2400e-01,
         9.1100e-01],
       [ 1.0499e+01,  9.3500e-01,  6.7906e+01,  7.7300e-01, -2.0300e-01,
         8.2600e-01],
       [ 1.0481e+01,  9.4100e-01,  6.8800e+01,  9.0900e-01, -1.0600e-01,
         5.2700e-01],
       [ 1.0382e+01,  8.9800e-01,  6.9702e+01,  8.4100e-01, -1.6500e-01,
         7.3500e-01],
       [ 1.0284e+01,  8.3200e-01,  6.7355e+01,  8.4500e-01, -2.1900e-01,
         9.3800e-01],
       [ 9.7870e+00,  8.7300e-01,  6.8600e+01,  7.7800e-01,  2.0000e-03,
         8.3500e-01],
       [ 1.0315e+01,  9.2700e-01,  6.7100e+01,  7.1500e-01, -1.6200e-01,
         8.0000e-01],
       [ 1.0358e+01,  9.4300e-01,  6.8000e+01,  7.

d. Increase the GDP per capita values in *ind_data* by 10%

In [57]:
ind_data[:,0]*=1.1
ind_data

array([[ 1.16116e+01,  9.47000e-01,  7.08070e+01,  8.58000e-01,
        -2.08000e-01,  8.68000e-01],
       [ 1.15819e+01,  9.48000e-01,  7.14000e+01,  9.49000e-01,
        -1.01000e-01,  8.06000e-01],
       [ 1.02498e+01,  8.21000e-01,  6.38130e+01,  8.69000e-01,
         2.57000e-01,  9.17000e-01],
       [ 1.14059e+01,  9.36000e-01,  6.92010e+01,  7.66000e-01,
        -1.24000e-01,  9.11000e-01],
       [ 1.15489e+01,  9.35000e-01,  6.79060e+01,  7.73000e-01,
        -2.03000e-01,  8.26000e-01],
       [ 1.15291e+01,  9.41000e-01,  6.88000e+01,  9.09000e-01,
        -1.06000e-01,  5.27000e-01],
       [ 1.14202e+01,  8.98000e-01,  6.97020e+01,  8.41000e-01,
        -1.65000e-01,  7.35000e-01],
       [ 1.13124e+01,  8.32000e-01,  6.73550e+01,  8.45000e-01,
        -2.19000e-01,  9.38000e-01],
       [ 1.07657e+01,  8.73000e-01,  6.86000e+01,  7.78000e-01,
         2.00000e-03,  8.35000e-01],
       [ 1.13465e+01,  9.27000e-01,  6.71000e+01,  7.15000e-01,
        -1.62000e-01,  8.00

e. Display the names of the countries in Latin America and Caribbean

In [77]:
country_names=np.where(country_data[:,0]== "Latin America and Caribbean")
print(country_data[country_names][:,1])

['Argentina' 'Bolivia' 'Brazil' 'Chile' 'Colombia' 'Costa Rica'
 'Dominican Republic' 'Ecuador' 'El Salvador' 'Guatemala' 'Haiti'
 'Honduras' 'Jamaica' 'Mexico' 'Nicaragua' 'Panama' 'Paraguay' 'Peru'
 'Uruguay' 'Venezuela']


f. Display the healthy life expectancy values for the countries in Latin America and Caribbean

In [79]:
ind_data[country_names,2]

array([[69.201, 68.699, 65.474, 67.055, 62.409, 69.6  , 69.593, 71.4  ,
        69.1  , 68.25 , 63.901, 65.9  , 66.005, 67.102, 53.78 , 50.102,
        51.969, 56.101, 72.2  , 73.8  ]])

g. Find and display the mean life expectancy value for all countries

In [86]:
mean=np.mean(ind_data[:,2])
mean

64.99279865771811

h. Find the countries above average life expectancy and store them as countries

In [99]:
countrys_above = np.where(ind_data[:,2]>mean)

countrys_above_mean=country_data[countrys_above][:,1]
print(countrys_above_mean)

['Afghanistan' 'Albania' 'Argentina' 'Armenia' 'Australia' 'Austria'
 'Azerbaijan' 'Bahrain' 'Bangladesh' 'Belarus' 'Belgium' 'Benin' 'Bolivia'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'Bulgaria' 'Burkina Faso'
 'Burundi' 'Cameroon' 'Chile' 'China' 'Costa Rica' 'Croatia' 'Cyprus'
 'Denmark' 'Dominican Republic' 'Ecuador' 'El Salvador' 'Estonia'
 'Ethiopia' 'Finland' 'France' 'Gabon' 'Gambia' 'Georgia' 'Germany'
 'Ghana' 'Greece' 'Guatemala' 'Guinea' 'Honduras'
 'Hong Kong S.A.R. of China' 'Hungary' 'India' 'Indonesia' 'Iran' 'Iraq'
 'Ireland' 'Italy' 'Ivory Coast' 'Jamaica' 'Jordan' 'Kazakhstan' 'Kenya'
 'Kuwait' 'Latvia' 'Lebanon' 'Lesotho' 'Liberia' 'Lithuania' 'Malawi'
 'Mali' 'Malta' 'Mauritius' 'Mexico' 'Mozambique' 'Switzerland'
 'Taiwan Province of China' 'Tajikistan' 'Tanzania' 'Thailand' 'Togo'
 'Tunisia' 'Turkey' 'Turkmenistan' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States' 'Uruguay'
 'Uzbekistan' 'Venezuela' 'Vietnam' 'Yemen' 'Zambia' 'Zimba

i.  Find the life expectancy of the countries above average life expectancy and store them as life

In [101]:
np.mean(ind_data[countrys_above,2])

69.69568181818181

j. Create a two dimensional array life_data where the first column contains the names of the countries with life expentancy above average life expectancy and the second column is the life expectancy of those countries.

In [109]:
temp = ind_data[countrys_above][:,2]
life_data=np.hstack([countrys_above_mean.reshape(len(countrys_above_mean),1),temp.reshape(len(temp),1),])


k. Display the countries and their life expectancy (life_data) from step j.

In [108]:
print(life_data)

[['Afghanistan' '70.807']
 ['Albania' '71.4']
 ['Argentina' '69.201']
 ['Armenia' '67.906']
 ['Australia' '68.8']
 ['Austria' '69.702']
 ['Azerbaijan' '67.355']
 ['Bahrain' '68.6']
 ['Bangladesh' '67.1']
 ['Belarus' '68.0']
 ['Belgium' '70.799']
 ['Benin' '68.098']
 ['Bolivia' '68.699']
 ['Bosnia and Herzegovina' '67.0']
 ['Botswana' '68.999']
 ['Brazil' '65.474']
 ['Bulgaria' '65.255']
 ['Burkina Faso' '65.2']
 ['Burundi' '65.699']
 ['Cameroon' '66.253']
 ['Chile' '67.055']
 ['China' '65.656']
 ['Costa Rica' '69.6']
 ['Croatia' '75.1']
 ['Cyprus' '73.9']
 ['Denmark' '76.82']
 ['Dominican Republic' '69.593']
 ['Ecuador' '71.4']
 ['El Salvador' '69.1']
 ['Estonia' '66.601']
 ['Ethiopia' '68.597']
 ['Finland' '67.5']
 ['France' '69.652']
 ['Gabon' '70.0']
 ['Gambia' '66.402']
 ['Georgia' '68.001']
 ['Germany' '67.657']
 ['Ghana' '69.0']
 ['Greece' '67.3']
 ['Guatemala' '68.25']
 ['Guinea' '68.8']
 ['Honduras' '65.9']
 ['Hong Kong S.A.R. of China' '66.102']
 ['Hungary' '66.7']
 ['India' '

l. Output the data to a file *above_life_expectancy.txt*

In [112]:
np.savetxt("above_life_expectancy.txt",life_data,fmt="%s")

m. Display the regions with at least 1 country with GDP per capita over 11 (no duplicates)

In [122]:
gdp_per_capita_over = np.where(ind_data[:,0]>11)
over_gdp = country_data[gdp_per_capita_over][:,0]
np.unique(over_gdp)

array(['Central and Eastern Europe', 'Commonwealth of Independent States',
       'East Asia', 'Latin America and Caribbean',
       'Middle East and North Africa', 'North America and ANZ',
       'South Asia', 'Southeast Asia', 'Sub-Saharan Africa',
       'Western Europe'], dtype='<U34')